name: Cleanup GHCR

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  cleanup:
    permissions:
      packages: write
    uses: s3ntin3l8/.github/.github/workflows/ghcr-cleanup.yml@main
    with:
      package-name: "${{ github.event.repository.name }}"
