name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: s3ntin3l8/.github/.github/workflows/release-please.yml@main

  build-docker:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: s3ntin3l8/.github/.github/workflows/docker-publish.yml@main
    with:
      image-name: "s3ntin3l8/${{ github.event.repository.name }}"
      push-release: true
      release-tag: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit # pragma: allowlist secret
